# Generated by Django 2.2.12 on 2020-05-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20200520_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='expense_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
