# Generated by Django 2.2.12 on 2020-05-21 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_auto_20200520_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='author',
        ),
    ]
