# Generated by Django 2.2.12 on 2020-05-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200518_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='text',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
